# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stdf_cpp <- function(x, k, R, alpha) {
    .Call(`_ReIns_stdf_cpp`, x, k, R, alpha)
}

stdf2_cpp <- function(x, k, X) {
    .Call(`_ReIns_stdf2_cpp`, x, k, X)
}

spliceEM_splicefit_raw_Rexport <- function(pi, theta, shape, beta, gamma, lower1, lower2, lower3, lower4, lower5, upper3, upper4, upper5, trunclower, tsplice, truncupper, eps, beta_tol, maxiter) {
    .Call(`_ReIns_spliceEM_splicefit_raw_Rexport`, pi, theta, shape, beta, gamma, lower1, lower2, lower3, lower4, lower5, upper3, upper4, upper5, trunclower, tsplice, truncupper, eps, beta_tol, maxiter)
}

spliceEM_shape_adj_Rexport <- function(pi, theta, shape, beta, gamma, lower1, lower2, lower3, lower4, lower5, upper3, upper4, upper5, trunclower, tsplice, truncupper, eps, beta_tol, maxiter) {
    .Call(`_ReIns_spliceEM_shape_adj_Rexport`, pi, theta, shape, beta, gamma, lower1, lower2, lower3, lower4, lower5, upper3, upper4, upper5, trunclower, tsplice, truncupper, eps, beta_tol, maxiter)
}

spliceEM_shape_red <- function(pi_in, theta_in, shape_in, beta_in, gamma_in, lower1, lower2, lower3, lower4, lower5, upper3, upper4, upper5, trunclower, tsplice, truncupper, criterium, improve, eps, beta_tol, maxiter, adj) {
    .Call(`_ReIns_spliceEM_shape_red`, pi_in, theta_in, shape_in, beta_in, gamma_in, lower1, lower2, lower3, lower4, lower5, upper3, upper4, upper5, trunclower, tsplice, truncupper, criterium, improve, eps, beta_tol, maxiter, adj)
}

